import { QueryClientProvider } from '@/shared/query_client.provider'
import { EffectorNext } from '@effector/next'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import type { ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="ru">
			<body className={inter.className}>
				<aside>
					<nav>
						<Link href="/examples/responsive-table">Responsive Table</Link>
						<Link href="/examples/react-query/todos">React Query todos</Link>
					</nav>
				</aside>
				<EffectorNext>
					<QueryClientProvider>{children}</QueryClientProvider>
				</EffectorNext>
			</body>
		</html>
	)
}
